# Generated by Django 3.2 on 2023-12-15 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MaxValueValidator(25.0), django.core.validators.MinValueValidator(1)]),
        ),
    ]
