# Generated by Django 3.2 on 2023-12-15 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank='true', default=datetime.datetime(2023, 12, 15, 17, 46, 37, 257146)),
        ),
    ]
